# Generated by Django 6.0.2 on 2026-02-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="domain",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Verification"),
                    ("ACTIVE", "Active"),
                    ("FAILED", "Verification Failed"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
