# Generated by Django 6.0.2 on 2026-02-12 05:51

import tenants.infrastructure.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_domain_is_custom_domain_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=tenants.infrastructure.utils.storage.tenant_path
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="primary_color",
            field=models.CharField(
                default="#000000", help_text="Hex color code", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="secondary_color",
            field=models.CharField(
                default="#ffffff", help_text="Hex color code", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="support_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
