# Generated by Django 6.0.2 on 2026-02-12 05:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_tenant_logo_tenant_primary_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="config",
            field=models.JSONField(
                blank=True, default=dict, help_text="Dynamic tenant-specific settings"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="is_maintenance",
            field=models.BooleanField(
                default=False, help_text="If True, all requests return 503"
            ),
        ),
        migrations.CreateModel(
            name="Quota",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resource_name",
                    models.CharField(
                        help_text="e.g., 'max_products', 'max_members'", max_length=50
                    ),
                ),
                (
                    "limit_value",
                    models.IntegerField(
                        default=0,
                        help_text="0 means unlimited or restricted depending on logic",
                    ),
                ),
                ("current_usage", models.IntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "resource_name")},
            },
        ),
    ]
