# Generated by Django 6.0.2 on 2026-02-12 14:39

import django.db.models.deletion
import tenants.infrastructure.storage.factory
import tenants.infrastructure.storage.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0009_plan_tenant_plan_webhook_webhookevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="impersonator",
            field=models.ForeignKey(
                blank=True,
                help_text="The staff member who performed this action while acting as the user.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="impersonated_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="billing_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="billing_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="country_code",
            field=models.CharField(
                default="US", help_text="ISO 2-letter country code", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="ip_whitelist",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="tenant",
            name="isolation_mode",
            field=models.CharField(
                choices=[
                    ("LOGICAL", "Logical Isolation (Shared Table)"),
                    ("PHYSICAL", "Physical Isolation (PostgreSQL Schema)"),
                ],
                default="LOGICAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="preferred_currency",
            field=models.CharField(
                default="USD",
                help_text="ISO 3-letter currency code (e.g., USD, EUR, GBP)",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="security_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tenant",
            name="smtp_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tenant",
            name="sso_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tenant",
            name="storage_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tenant",
            name="subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="subscription_status",
            field=models.CharField(
                default="active",
                help_text="active, past_due, trialing, canceled",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="tax_id",
            field=models.CharField(
                blank=True, help_text="VAT/GST/EIN", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quota",
            name="limit_value",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="quota",
            name="resource_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="is_maintenance",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=tenants.infrastructure.storage.factory.get_tenant_storage,
                upload_to=tenants.infrastructure.storage.utils.tenant_storage_path,
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="events",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="secret",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="BillingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GovernanceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("PURGE", "Permanent Organization Purge"),
                            ("EXPORT", "Sensitive Data Export"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXECUTED", "Executed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="governance_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="governance_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RevenueEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("recognized_date", models.DateField()),
                ("description", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(default="subscription", max_length=50),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Revenue entries",
            },
        ),
        migrations.CreateModel(
            name="TenantCreditWallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_credits",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
                ),
                (
                    "spent_credits",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
                ),
                ("last_recharge_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TenantMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_name", models.CharField(max_length=100)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("unit", models.CharField(default="count", max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Entitlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("feature_code", models.CharField(max_length=100)),
                ("is_enabled", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlements",
                        to="tenants.plan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "feature_code")},
            },
        ),
    ]
