# Generated by Django 6.0.2 on 2026-02-16 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0011_ledgeraccount_ledgerentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelemetryEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("SEARCH", "Search"),
                            ("CACHE", "Cache"),
                            ("IDENTITY", "Identity"),
                        ],
                        max_length=50,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("DEGRADED", "Degraded (Fallback Used)"),
                            ("CIRCUIT_OPEN", "Circuit Breaker Open"),
                        ],
                        max_length=20,
                    ),
                ),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Telemetry Entries",
                "ordering": ["-timestamp"],
            },
        ),
    ]
