# Generated by Django 6.0.2 on 2026-02-16 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0012_telemetryentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="locale",
            field=models.CharField(
                default="en-US", help_text="BCP 47 language tag", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent organization for hierarchical multi-tenancy",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="timezone",
            field=models.CharField(
                default="UTC", help_text="Olson timezone name", max_length=100
            ),
        ),
    ]
