from typing import Protocol, runtime_checkable, Any, Dict, List, Optional
from tenants.models import Tenant

@runtime_checkable
class IBillingProvider(Protocol):
    """
    Tier 52: Dependency Inversion Protocol.
    Defines the contract for all Billing Adapters.
    """
    def create_customer(self, tenant: Tenant) -> str: ...
    def create_subscription(self, tenant: Tenant, plan_id: str) -> str: ...
    def cancel_subscription(self, subscription_id: str) -> bool: ...
    def get_portal_url(self, tenant: Tenant) -> str: ...
    def update_quantity(self, subscription_id: str, quantity: int) -> bool: ...
    def verify_webhook(self, payload: Dict[str, Any], signature: str) -> bool: ...

@runtime_checkable
class IStorageProvider(Protocol):
    """Protocol for pluggable storage backends."""
    def upload_file(self, tenant: Tenant, file_obj: Any, path: str) -> str: ...
    def delete_file(self, tenant: Tenant, path: str) -> bool: ...
    def get_signed_url(self, tenant: Tenant, path: str) -> str: ...
