# Generated by Django 6.0.2 on 2026-02-11 13:18

import tenants.utils_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=tenants.utils_storage.tenant_file_path
            ),
        ),
    ]
